// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejpuvnsduxhdcjspfqci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcHV2bnNkdXhoZGNqc3BmcWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDM5ODcsImV4cCI6MjA3MzYxOTk4N30.XBVkSwusRtkQ_C38Gr619p_Vs2BtonSwP45QHYN0728";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});